error: make ResultExt only public to the crate
`ResultExt` was introduced as an internal utility for more convenient
conversion of inner errors to `Error`. We never really intended to leak
it.