error: add trait for augmenting inner errors with associated types
Currently, this library relies on the `git2` crate for accessing git
repositories. In the future, however, we want to enable our users to
choose between that and other git implementations (such as the
`git-repository` crate). A recurring pattern will be traits with one
implementation for each library we support.

Many functions may fail in one way or another and failures may often
originate from the git library. Our current `Error` can therefore wrap
a `git2::Error`. If we want to support additional libraries, our `Error`
needs the ability to wrap error types specific to those libraries. At
the same time, we neither need nor want to support mixing git libraries.
Making `Error` generic over the "inner" `Error` type should be
sufficient.

This still leaves us with our current usage of `git2::Oid` in our error
types, which becomes problematic when _not_ using `git2`. Upon closer
inspection, we may also choose specific types for representing git
references inside errors for some git library. We thus decided to
associate these types to the git library specific error type, and we
choose to do so via a trait which we'll implement for the specific error
types.

This change introduces this trait, preparing the general error utility
overhaul.